SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE SCHEMA IF NOT EXISTS `tree_nodes` ;
USE `tree_nodes` ;

-- -----------------------------------------------------
-- Table `tree_nodes`.`categories_has_listings`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `tree_nodes`.`categories_has_listings` (
  `category_id` INT(11) NOT NULL ,
  `listing_id` INT(11) NOT NULL ,
  PRIMARY KEY (`category_id`, `listing_id`) ,
  INDEX `fk_categories_has_listings_listings1` (`listing_id` ASC) ,
  INDEX `fk_categories_has_listings_categories` (`category_id` ASC) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tree_nodes`.`category`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `tree_nodes`.`category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT ,
  `id_type` INT(11) NOT NULL DEFAULT '0' ,
  `id_parent` INT(11) NOT NULL DEFAULT '0' ,
  `order_num` INT(11) NOT NULL ,
  `name` VARCHAR(255) NULL DEFAULT NULL ,
  `seo_name` VARCHAR(255) NOT NULL DEFAULT '' ,
  `selected_icons_serialized` INT(15) NOT NULL ,
  `meta_title` VARCHAR(255) NOT NULL ,
  `meta_description` VARCHAR(255) NOT NULL ,
  PRIMARY KEY (`id`) ,
  INDEX `parent_category_id` (`id_parent` ASC) ,
  FULLTEXT INDEX `name` (`name` ASC, `meta_title` ASC, `meta_description` ASC) ,
  FULLTEXT INDEX `meta_title` (`meta_title` ASC) )
ENGINE = MyISAM
AUTO_INCREMENT = 468
DEFAULT CHARACTER SET = utf8
PACK_KEYS = 0;

--
-- Daten für Tabelle `category`
--

INSERT INTO `category` (`id`, `id_type`, `id_parent`, `order_num`, `name`, `seo_name`, `selected_icons_serialized`, `meta_title`, `meta_description`) VALUES
(1, 0, 0, 0, 'Dienstleistungen & Services', 'Dienstleistungen und Services', 0, '', ''),
(2, 0, 0, 0, 'Finanzen & Recht', 'Finanzen und Recht', 0, '', ''),
(3, 0, 0, 0, 'Essen, Trinken & Unterhaltung', 'Essen, Trinken und Unterhaltung', 0, '', ''),
(4, 0, 0, 0, 'Gesundheit', 'Gesundheit', 0, '', ''),
(5, 0, 0, 0, 'Gruppen & Vereine', 'Gruppen und Vereine', 0, '', ''),
(6, 0, 0, 0, 'Hotel & Reisen', 'Hotel und Reisen', 0, '', ''),
(7, 0, 0, 0, 'Shopping', 'Shopping', 0, '', ''),
(8, 0, 1, 0, 'Auto & Transport', 'Auto und Transport', 0, '', ''),
(9, 0, 8, 0, 'Abschleppdienst', 'Abschleppdienst', 0, '', ''),
(10, 0, 8, 0, 'Airportservice', 'Airportservice', 0, '', ''),
(11, 0, 8, 0, 'Autoclubs', 'Autoclubs', 0, '', ''),
(12, 0, 8, 0, 'Autohaus', 'Autohaus', 0, '', ''),
(13, 0, 8, 0, 'Autoreparaturen/ KFZ & Motorrad Service, KFZ Gutachter', 'Autoreparaturen/ KFZ & Motorrad Service, KFZ Gutachter', 0, '', ''),
(14, 0, 8, 0, 'Autovermietungen ', 'Autovermietungen ', 0, '', ''),
(15, 0, 8, 0, 'Autowäscherei', 'Autowäscherei', 0, '', ''),
(16, 0, 8, 0, 'Carsharing', 'Carsharing', 0, '', ''),
(17, 0, 8, 0, 'Fahrradservice/Reparatur', 'Fahrradservice/Reparatur', 0, '', ''),
(18, 0, 8, 0, 'Fahrschule', 'Fahrschule', 0, '', ''),
(19, 0, 8, 0, 'Kurierdienst', 'Kurierdienst', 0, '', ''),
(20, 0, 8, 0, 'Spedition/Frachttransport', 'Spedition/Frachttransport', 0, '', ''),
(21, 0, 8, 0, 'Tankstellen', 'Tankstellen', 0, '', ''),
(22, 0, 8, 0, 'Taxi & Fuhrunternehmen', 'Taxi & Fuhrunternehmen', 0, '', ''),
(23, 0, 8, 0, 'Transportunternehmen', 'Transportunternehmen', 0, '', ''),
(24, 0, 8, 0, 'TÜV/DEKRA', 'TÜV/DEKRA', 0, '', ''),
(25, 0, 8, 0, 'Umzüge', 'Umzüge', 0, '', ''),
(26, 0, 1, 0, 'Medien, Verlage & Presse', 'Medien, Verlage & Presse', 0, '', ''),
(27, 0, 26, 0, 'Journalisten', 'Journalisten', 0, '', ''),
(28, 0, 26, 0, 'Casting Agentur', 'Casting Agentur', 0, '', ''),
(29, 0, 26, 0, 'Lektorat', 'Lektorat', 0, '', ''),
(30, 0, 26, 0, 'Radiosender', 'Radiosender', 0, '', ''),
(31, 0, 26, 0, 'Texter', 'Texter', 0, '', ''),
(32, 0, 26, 0, 'TV Sender', 'TV Sender', 0, '', ''),
(33, 0, 26, 0, 'Verlage', 'Verlage', 0, '', ''),
(34, 0, 26, 0, 'Zeitungen & Zeitschriften', 'Zeitungen & Zeitschriften', 0, '', ''),
(35, 0, 1, 0, 'Handwerk', 'Handwerk', 0, '', ''),
(36, 0, 35, 0, 'Airbrush', 'Airbrush', 0, '', ''),
(37, 0, 35, 0, 'Bäder & Armaturen', 'Bäder und Armaturen', 0, '', ''),
(38, 0, 35, 0, 'Bilderrahmen', 'Bilderrahmen', 0, '', ''),
(39, 0, 35, 0, 'Böden, Fußbodenleger & Bodenleger ', 'Böden, Fußbodenleger und Bodenleger ', 0, '', ''),
(40, 0, 35, 0, 'Buchbinderei', 'Buchbinderei', 0, '', ''),
(41, 0, 35, 0, 'Dachdecker', 'Dachdecker', 0, '', ''),
(42, 0, 35, 0, 'Elektro, Elektroinstallation & Licht', 'Elektro, Elektroinstallation und Licht', 0, '', ''),
(43, 0, 35, 0, 'Fassade & Wand', 'Fassade & Wand', 0, '', ''),
(44, 0, 35, 0, 'Fenster, Türen & Tore', 'Fenster, Türen und Tore', 0, '', ''),
(45, 0, 35, 0, 'Glaserei', 'Glaserei', 0, '', ''),
(46, 0, 35, 0, 'Grabmalgestaltung & Grabmalpflege', 'Grabmalgestaltung und Grabmalpflege', 0, '', ''),
(47, 0, 35, 0, 'Handwerker', 'Handwerker', 0, '', ''),
(48, 0, 35, 0, 'Heizung-, Klima-, Lüftungs & Sanitärservice', 'Heizung-, Klima-, Lüftungs und Sanitärservice', 0, '', ''),
(49, 0, 35, 0, 'Klimaanlage,Klimatechnik & Belüftung', 'Klimaanlage,Klimatechnik und Belüftung', 0, '', ''),
(50, 0, 35, 0, 'Maler, Lackierer & Tapezierer', 'Maler, Lackierer und Tapezierer', 0, '', ''),
(51, 0, 35, 0, 'Markisen & Sonnenschutz', 'Markisen und Sonnenschutz', 0, '', ''),
(52, 0, 35, 0, 'Metallverabreitung', 'Metallverabreitung', 0, '', ''),
(53, 0, 35, 0, 'Radio & TV Reparatur', 'Radio und TV Reparatur', 0, '', ''),
(54, 0, 35, 0, 'Renovierungs-, Maler- & Umbauarbeiten', 'Renovierungs-, Maler- und Umbauarbeiten', 0, '', ''),
(55, 0, 35, 0, 'Ofen & Kamine', 'Ofen und Kamine', 0, '', ''),
(56, 0, 35, 0, 'Schreiner & Tischler', 'Schreiner und Tischler', 0, '', ''),
(57, 0, 35, 0, 'Schuhmacher & Schuster', 'Schuhmacher und Schuster', 0, '', ''),
(58, 0, 35, 0, 'Steinmetz', 'Steinmetz', 0, '', ''),
(59, 0, 35, 0, 'Türen & Tore', 'Türen und Tore', 0, '', ''),
(60, 0, 35, 0, 'Uhrenreparatur & Schmuckreparatur', 'Uhrenreparatur und Schmuckreparatur', 0, '', ''),
(61, 0, 1, 0, 'Telekommunikation & Sicherheit', 'Telekommunikation und Sicherheit', 0, '', ''),
(62, 0, 61, 0, 'Alarmanlagen & Sicherheitssysteme', 'Alarmanlagen und Sicherheitssysteme', 0, '', ''),
(63, 0, 61, 0, 'Büroelektronik & Bürotechnik', 'Büroelektronik und Bürotechnik', 0, '', ''),
(64, 0, 61, 0, 'Detektivbüro', 'Detektivbüro', 0, '', ''),
(65, 0, 61, 0, 'Schlüsseldienst', 'Schlüsseldienst', 0, '', ''),
(66, 0, 61, 0, 'Sicherheitsdienst', 'Sicherheitsdienst', 0, '', ''),
(67, 0, 61, 0, 'Telefone & Mobilfunk', 'Telefone und Mobilfunk', 0, '', ''),
(68, 0, 1, 0, 'Marketing & Werbung', 'Marketing und Werbung', 0, '', ''),
(69, 0, 68, 0, 'Flyerverteilung & Prospektverteilung', 'Flyerverteilung und Prospektverteilung', 0, '', ''),
(70, 0, 68, 0, 'Grafik - Grafikdesign', 'Grafik - Grafikdesign', 0, '', ''),
(71, 0, 68, 0, 'Internetplattform', 'Internetplattform', 0, '', ''),
(72, 0, 68, 0, 'Medien & Internet', 'Medien und Internet', 0, '', ''),
(73, 0, 68, 0, 'Verlage', 'Verlage', 0, '', ''),
(74, 0, 68, 0, 'Webdesign', 'Webdesign', 0, '', ''),
(75, 0, 1, 0, 'Computer & Elektronik ', 'Computer und Elektronik ', 0, '', ''),
(76, 0, 75, 0, 'Computer/IT Service/Web-Profi/Multimedia/EDV Systeme', 'Computer/IT Service/Web-Profi/Multimedia/EDV Systeme', 0, '', ''),
(77, 0, 75, 0, 'EDV Schulungen', 'EDV Schulungen', 0, '', ''),
(78, 0, 75, 0, 'Elektrotechniker', 'Elektrotechniker', 0, '', ''),
(79, 0, 75, 0, 'Softwareentwicklung', 'Softwareentwicklung', 0, '', ''),
(80, 0, 1, 0, 'Bestattung & Trauer', 'Bestattung und Trauer', 0, '', ''),
(81, 0, 80, 0, 'Bestattungen', 'Bestattungen', 0, '', ''),
(82, 0, 80, 0, 'Trauerredner', 'Trauerredner', 0, '', ''),
(83, 0, 80, 0, 'Trauerbegleitung & Seelsorge', 'Trauerbegleitung und Seelsorge', 0, '', ''),
(84, 0, 1, 0, 'Personaldienstleistungen & Jobs', 'Personaldienstleistungen und Jobs', 0, '', ''),
(85, 0, 84, 0, 'Zeitarbeitsfirma', 'Zeitarbeitsfirma', 0, '', ''),
(86, 0, 84, 0, 'Arbeitsvermittlung & Arbeitsagentur', 'Arbeitsvermittlung und Arbeitsagentur', 0, '', ''),
(87, 0, 84, 0, 'Personalberatung', 'Personalberatung', 0, '', ''),
(88, 0, 84, 0, 'Personaldienstleistung ', 'Personaldienstleistung ', 0, '', ''),
(89, 0, 1, 0, 'Schule & Bildung', 'Schule und Bildung', 0, '', ''),
(90, 0, 89, 0, 'Ballettschule', 'Ballettschule', 0, '', ''),
(91, 0, 89, 0, 'Ausbildung', 'Ausbildung', 0, '', ''),
(92, 0, 89, 0, 'Berufsschule', 'Berufsschule', 0, '', ''),
(93, 0, 89, 0, 'Fachschule', 'Fachschule', 0, '', ''),
(94, 0, 89, 0, 'Fortbildung', 'Fortbildung', 0, '', ''),
(95, 0, 89, 0, 'Gesangsunterricht', 'Gesangsunterricht', 0, '', ''),
(96, 0, 89, 0, 'Kochschule', 'Kochschule', 0, '', ''),
(97, 0, 89, 0, 'Musikschule & Musikunterricht', 'Musikschule und Musikunterricht', 0, '', ''),
(98, 0, 89, 0, 'Sprachunterricht', 'Sprachunterricht', 0, '', ''),
(99, 0, 89, 0, 'Tanzunterricht & Tanzschule', 'Tanzunterricht und Tanzschule', 0, '', ''),
(100, 0, 89, 0, 'Universität', 'Universität', 0, '', ''),
(101, 0, 89, 0, 'Filmakademie', 'Filmakademie', 0, '', ''),
(102, 0, 1, 0, 'Events, Catering & Austellungen', 'Events, Catering und Austellungen', 0, '', ''),
(103, 0, 102, 0, 'Catering, Partyservice, Lieferservice & Messe Catering', 'Catering, Partyservice, Lieferservice und Messe Catering', 0, '', ''),
(104, 0, 102, 0, 'DJ - Discjockey', 'DJ - Discjockey', 0, '', ''),
(105, 0, 102, 0, 'Eventmanagment, Künstlervermittlung & Eventkünstler', 'Eventmanagment, Künstlervermittlung und Eventkünstler', 0, '', ''),
(106, 0, 102, 0, 'Hochzeitsplaner & Hochzeitsredner', 'Hochzeitsplaner und Hochzeitsredner', 0, '', ''),
(107, 0, 102, 0, 'Licht & Lichttechnik', 'Licht und Lichttechnik', 0, '', ''),
(108, 0, 102, 0, 'Maskenbildner', 'Maskenbildner', 0, '', ''),
(109, 0, 102, 0, 'Partyorganisation & Showproduktion', 'Partyorganisation und Showproduktion', 0, '', ''),
(110, 0, 102, 0, 'Veranstaltungen, Veranstaltungsorganisation & Veranstaltungstechnik', 'Veranstaltungen, Veranstaltungsorganisation und Veranstaltungstechnik', 0, '', ''),
(111, 0, 102, 0, 'Messe & Kongresse', 'Messe und Kongresse', 0, '', ''),
(112, 0, 1, 0, 'Umwelt', 'Umwelt', 0, '', ''),
(113, 0, 112, 0, 'Bau & Energieberatung', 'Bau und Energieberatung', 0, '', ''),
(114, 0, 112, 0, 'Sanitärtechnik ', 'Sanitärtechnik ', 0, '', ''),
(115, 0, 112, 0, 'Solartechnik', 'Solartechnik', 0, '', ''),
(116, 0, 112, 0, 'Umwelttechnik', 'Umwelttechnik', 0, '', ''),
(117, 0, 112, 0, 'Windenergie', 'Windenergie', 0, '', ''),
(118, 0, 1, 0, 'Reinigung & Gebäudereinigung', 'Reinigung und Gebäudereinigung', 0, '', ''),
(119, 0, 118, 0, 'Müllentsorgung & Abfallwirtschaft', 'Müllentsorgung und Abfallwirtschaft', 0, '', ''),
(120, 0, 118, 0, 'Reinigung & Gebäudeservice', 'Reinigung und Gebäudeservice', 0, '', ''),
(121, 0, 118, 0, 'Spezialreinigung', 'Spezialreinigung', 0, '', ''),
(122, 0, 118, 0, 'Waschsalon & Wäscherei', 'Waschsalon und Wäscherei', 0, '', ''),
(123, 0, 118, 0, 'Werstoffhöfe', 'Werstoffhöfe', 0, '', ''),
(124, 0, 1, 0, 'Wohnen & Bauen ', 'Wohnen und Bauen ', 0, '', ''),
(125, 0, 124, 0, 'Innenarchitekt', 'Innenarchitekt', 0, '', ''),
(126, 0, 124, 0, 'Architektur', 'Architektur', 0, '', ''),
(127, 0, 124, 0, 'Bau & Grundstücksgutachter', 'Bau und Grundstücksgutachter', 0, '', ''),
(128, 0, 124, 0, 'Bauunternehmen', 'Bauunternehmen', 0, '', ''),
(129, 0, 124, 0, 'Dekoration', 'Dekoration', 0, '', ''),
(130, 0, 124, 0, 'Designer & Wohnkonzepte', 'Designer und Wohnkonzepte', 0, '', ''),
(131, 0, 124, 0, 'Grundstücks- & Verkehrsgesellschaften', 'Grundstücks- und Verkehrsgesellschaften', 0, '', ''),
(132, 0, 124, 0, 'Haushaltsauflösung & Entrümpeln', 'Haushaltsauflösung und Entrümpeln', 0, '', ''),
(133, 0, 124, 0, 'Hausmeister', 'Hausmeister', 0, '', ''),
(134, 0, 124, 0, 'Haustechnik', 'Haustechnik', 0, '', ''),
(135, 0, 124, 0, 'Hausverwaltungen', 'Hausverwaltungen', 0, '', ''),
(136, 0, 124, 0, 'Immobilien', 'Immobilien', 0, '', ''),
(137, 0, 124, 0, 'Ingenieurbüro', 'Ingenieurbüro', 0, '', ''),
(138, 0, 124, 0, 'Küchentechnik, Küchenkonzepte & Planung', 'Küchentechnik, Küchenkonzepte und Planung', 0, '', ''),
(139, 0, 124, 0, 'Massivhaushersteller', 'Massivhaushersteller', 0, '', ''),
(140, 0, 124, 0, 'Mietberatung & Mieterbund', 'Mietberatung und Mieterbund', 0, '', ''),
(141, 0, 124, 0, 'Treppen & Aufzüge', 'Treppen und Aufzüge', 0, '', ''),
(142, 0, 124, 0, 'Wohnungsbau & Sanierungsbau ', 'Wohnungsbau und Sanierungsbau ', 0, '', ''),
(143, 0, 1, 0, 'Foto & Film ', 'Foto und Film ', 0, '', ''),
(144, 0, 143, 0, 'Filmproduktion &  Verleih', 'Filmproduktion und  Verleih', 0, '', ''),
(145, 0, 143, 0, 'Fotografie & Fotostudio', 'Fotografie und Fotostudio', 0, '', ''),
(146, 0, 143, 0, 'Musikproduktion & Tonstudio ', 'Musikproduktion und Tonstudio ', 0, '', ''),
(147, 0, 1, 0, 'Tiere & Pflege ', 'Tiere und Pflege ', 0, '', ''),
(148, 0, 147, 0, 'Hundepflege, Tierpflege & Tierheime', 'Hundepflege, Tierpflege und Tierheime', 0, '', ''),
(149, 0, 147, 0, 'Tierfriedhof', 'Tierfriedhof', 0, '', ''),
(150, 0, 1, 0, 'Sonstiges', 'Sonstiges', 0, '', ''),
(151, 0, 150, 0, 'Automatenservice', 'Automatenservice', 0, '', ''),
(152, 0, 150, 0, 'Bibliothek', 'Bibliothek', 0, '', ''),
(153, 0, 150, 0, 'Casting Agentur', 'Casting Agentur', 0, '', ''),
(154, 0, 150, 0, 'Feng Shui Berater', 'Feng Shui Berater', 0, '', ''),
(155, 0, 150, 0, 'Gebärden Dolmetscher', 'Gebärden Dolmetscher', 0, '', ''),
(156, 0, 150, 0, 'Großhandel', 'Großhandel', 0, '', ''),
(157, 0, 150, 0, 'Klavierstimmer', 'Klavierstimmer', 0, '', ''),
(158, 0, 150, 0, 'Leihhaus', 'Leihhaus', 0, '', ''),
(159, 0, 150, 0, 'Leihköche & Privatkoch', 'Leihköche und Privatkoch', 0, '', ''),
(160, 0, 150, 0, 'Partnervermittlung', 'Partnervermittlung', 0, '', ''),
(161, 0, 150, 0, 'Schneiderei & Änderungsschneiderei/Maßschneiderei', 'Schneiderei und Änderungsschneiderei/Maßschneiderei', 0, '', ''),
(162, 0, 150, 0, 'Übersetzer & Dolmetscher', 'Übersetzer und Dolmetscher', 0, '', ''),
(163, 0, 2, 0, 'Versicherungen', 'Versicherungen', 0, '', ''),
(164, 0, 163, 0, 'Versicherungen & Vers. Agenturen', 'Versicherungen und Vers. Agenturen', 0, '', ''),
(165, 0, 163, 0, 'Autoversicherungen', 'Autoversicherungen', 0, '', ''),
(166, 0, 163, 0, 'Berufsunfähigkeitsversicherung', 'Berufsunfähigkeitsversicherung', 0, '', ''),
(167, 0, 163, 0, 'Krankenversicherung & Krankenkasse', 'Krankenversicherung und Krankenkasse', 0, '', ''),
(168, 0, 163, 0, 'Versicherungsagenturen', 'Versicherungsagenturen', 0, '', ''),
(169, 0, 163, 0, 'Versicherungsvermittlung', 'Versicherungsvermittlung', 0, '', ''),
(170, 0, 163, 0, 'Lebensversicherungen', 'Lebensversicherungen', 0, '', ''),
(171, 0, 163, 0, 'Rechtschutzversicherungen', 'Rechtschutzversicherungen', 0, '', ''),
(172, 0, 163, 0, 'Rentenversicherungen & Altersvorsorge', 'Rentenversicherungen und Altersvorsorge', 0, '', ''),
(173, 0, 163, 0, 'Direktversicherungen', 'Direktversicherungen', 0, '', ''),
(174, 0, 163, 0, 'KFZ Versicherung/Autoversicherung', 'KFZ Versicherung/Autoversicherung', 0, '', ''),
(175, 0, 163, 0, 'Unfallversicherung', 'Unfallversicherung', 0, '', ''),
(176, 0, 2, 0, 'Recht', 'Recht', 0, '', ''),
(177, 0, 176, 0, 'Rechtsanwälte ', 'Rechtsanwälte ', 0, '', ''),
(178, 0, 176, 0, 'Rechtsanwälte für Lebenspartnerschaften', 'Rechtsanwälte für Lebenspartnerschaften', 0, '', ''),
(179, 0, 176, 0, 'Rechtsberatung Rente', 'Rechtsberatung Rente', 0, '', ''),
(180, 0, 176, 0, 'Adoptionsrechtsberatung', 'Adoptionsrechtsberatung', 0, '', ''),
(181, 0, 176, 0, 'Patentanwälte', 'Patentanwälte', 0, '', ''),
(182, 0, 176, 0, 'Mieterberatung', 'Mieterberatung', 0, '', ''),
(183, 0, 176, 0, 'Patientenverfügungen & Testamente', 'Patientenverfügungen und Testamente', 0, '', ''),
(184, 0, 176, 0, 'Medizinische Rechtsberatung', 'Medizinische Rechtsberatung', 0, '', ''),
(185, 0, 176, 0, 'Nachlassverwaltung', 'Nachlassverwaltung', 0, '', ''),
(186, 0, 2, 0, 'Steuerberater', 'Steuerberater', 0, '', ''),
(187, 0, 186, 0, 'Lohnsteuerhilfeverein', 'Lohnsteuerhilfeverein', 0, '', ''),
(188, 0, 186, 0, 'Wirtschaftsprüfung', 'Wirtschaftsprüfung', 0, '', ''),
(189, 0, 186, 0, 'Büroservice, Buchhaltung & Rechnungswesen', 'Büroservice, Buchhaltung und Rechnungswesen', 0, '', ''),
(190, 0, 2, 0, 'Lohnsteuerhilfeverein (DE)', 'Lohnsteuerhilfeverein (DE)', 0, '', ''),
(191, 0, 2, 0, 'Notare', 'Notare', 0, '', ''),
(192, 0, 2, 0, 'Unternehmensberatung – Coaching', 'Unternehmensberatung – Coaching', 0, '', ''),
(193, 0, 2, 0, 'Anlage & Finanzierung', 'Anlage und Finanzierung', 0, '', ''),
(194, 0, 193, 0, 'Leasing', 'Leasing', 0, '', ''),
(195, 0, 193, 0, 'Vermögensverwaltung & Finanzdienstleistung', 'Vermögensverwaltung und Finanzdienstleistung', 0, '', ''),
(196, 0, 193, 0, 'Investmentberater', 'Investmentberater', 0, '', ''),
(197, 0, 193, 0, 'Goldankauf & Edelmetalle', 'Goldankauf und Edelmetalle', 0, '', ''),
(198, 0, 2, 0, 'Banken', 'Banken', 0, '', ''),
(199, 0, 2, 0, 'Bausparkasse', 'Bausparkasse', 0, '', ''),
(200, 0, 2, 0, 'Inkassobüro', 'Inkassobüro', 0, '', ''),
(201, 0, 2, 0, 'Schuldnerberatung', 'Schuldnerberatung', 0, '', ''),
(202, 0, 2, 0, 'Existenzgründungsberatung', 'Existenzgründungsberatung', 0, '', ''),
(203, 0, 2, 0, 'Sachverständige', 'Sachverständige', 0, '', ''),
(204, 0, 2, 0, 'Verbraucherzentrale', 'Verbraucherzentrale', 0, '', ''),
(205, 0, 2, 0, 'Bewerbung & Karriere', 'Bewerbung und Karriere', 0, '', ''),
(206, 0, 2, 0, 'Verbraucherzentrale & Beratung', 'Verbraucherzentrale und Beratung', 0, '', ''),
(207, 0, 3, 0, 'Bars, Kneipen, Lounge & Pubs', 'Bars, Kneipen, Lounge und Pubs', 0, '', ''),
(208, 0, 3, 0, 'Restaurants ', 'Restaurants ', 0, '', ''),
(209, 0, 208, 0, 'ASIA, Thai, China, Indien usw.', 'ASIA, Thai, China, Indien usw.', 0, '', ''),
(210, 0, 208, 0, 'Baggel & Donuts  ', 'Baggel und Donuts  ', 0, '', ''),
(211, 0, 208, 0, 'Biergarten ', 'Biergarten ', 0, '', ''),
(212, 0, 208, 0, 'Bio Imbiss, Bio-Restaurant & Bistro', 'Bio Imbiss, Bio-Restaurant und Bistro', 0, '', ''),
(213, 0, 208, 0, 'Brauerei', 'Brauerei', 0, '', ''),
(214, 0, 208, 0, 'Feinkost', 'Feinkost', 0, '', ''),
(215, 0, 208, 0, 'Fisch Imbiss, Fisch Restaurant & Seafood', 'Fisch Imbiss, Fisch Restaurant und Seafood', 0, '', ''),
(216, 0, 208, 0, 'Pizzeria, Ristorante & Trattoria', 'Pizzeria, Ristorante und Trattoria', 0, '', ''),
(217, 0, 208, 0, 'Steakhouse & Grill', 'Steakhouse und Grill', 0, '', ''),
(218, 0, 208, 0, 'Sushi', 'Sushi', 0, '', ''),
(219, 0, 208, 0, 'Vegan Restaurant', 'Vegan Restaurant', 0, '', ''),
(220, 0, 208, 0, 'Vegetarisches Restaurant', 'Vegetarisches Restaurant', 0, '', ''),
(221, 0, 3, 0, 'Cafés, Coffeshops & Konditorei', 'Cafés, Coffeshops und Konditorei', 0, '', ''),
(222, 0, 3, 0, 'Fastfood', 'Fastfood', 0, '', ''),
(223, 0, 3, 0, 'Discos, Partys & Clubs', 'Discos, Partys und Clubs', 0, '', ''),
(224, 0, 3, 0, 'Casino & Spielhallen', 'Casino und Spielhallen', 0, '', ''),
(225, 0, 3, 0, 'Kunst & Kultur', 'Kunst und Kultur', 0, '', ''),
(226, 0, 225, 0, 'Ausstellung & Galerien ', 'Ausstellung und Galerien ', 0, '', ''),
(227, 0, 225, 0, 'Kabaret, Travestie & Varieté', 'Kabaret, Travestie und Varieté', 0, '', ''),
(228, 0, 225, 0, 'Kino & Film', 'Kino und Film', 0, '', ''),
(229, 0, 225, 0, 'Komödie & Schauspielhaus', 'Komödie und Schauspielhaus', 0, '', ''),
(230, 0, 225, 0, 'Konzerthalle, Philharmonie, Oper & Operette', 'Konzerthalle, Philharmonie, Oper und Operette', 0, '', ''),
(231, 0, 225, 0, 'Museen', 'Museen', 0, '', ''),
(232, 0, 225, 0, 'Musical', 'Musical', 0, '', ''),
(233, 0, 225, 0, 'Stadtführung & Stadtrundfahrten', 'Stadtführung und Stadtrundfahrten', 0, '', ''),
(234, 0, 225, 0, 'Theater ', 'Theater ', 0, '', ''),
(235, 0, 225, 0, 'Events', 'Events', 0, '', ''),
(236, 0, 3, 0, 'Eiscafes & Eisdielen', 'Eiscafes und Eisdielen', 0, '', ''),
(237, 0, 3, 0, 'Kartenvorverkauf & Ticketcenter', 'Kartenvorverkauf und Ticketcenter', 0, '', ''),
(238, 0, 3, 0, 'Internetcafe', 'Internetcafe', 0, '', ''),
(239, 0, 3, 0, 'Kutschfahrten & Rikscha', 'Kutschfahrten und Rikscha', 0, '', ''),
(240, 0, 3, 0, 'Fetisch & Lederbar', 'Fetisch und Lederbar', 0, '', ''),
(241, 0, 3, 0, 'Sonnenstudio & Solarium', 'Sonnenstudio und Solarium', 0, '', ''),
(242, 0, 3, 0, 'Nachtclubs', 'Nachtclubs', 0, '', ''),
(243, 0, 3, 0, 'Bowling (Kegeln) ', 'Bowling (Kegeln) ', 0, '', ''),
(244, 0, 3, 0, 'Kiosk & Imbiss', 'Kiosk und Imbiss', 0, '', ''),
(245, 0, 3, 0, 'Auktion & Versteigerung', 'Auktion und Versteigerung', 0, '', ''),
(246, 0, 3, 0, 'Kurhaus ', 'Kurhaus ', 0, '', ''),
(247, 0, 4, 0, 'Ärzte', 'Ärzte', 0, '', ''),
(248, 0, 247, 0, 'Akupunktur', 'Akupunktur', 0, '', ''),
(249, 0, 247, 0, 'Allergologie', 'Allergologie', 0, '', ''),
(250, 0, 247, 0, 'Allgemeinmedizin & Praktische Ärzte', 'Allgemeinmedizin und Praktische Ärzte', 0, '', ''),
(251, 0, 247, 0, 'Anästhesiologie', 'Anästhesiologie', 0, '', ''),
(252, 0, 247, 0, 'Augenheilkunde & Augenarzt', 'Augenheilkunde und Augenarzt', 0, '', ''),
(253, 0, 247, 0, 'Chiropraktik & Osteopathie', 'Chiropraktik und Osteopathie', 0, '', ''),
(254, 0, 247, 0, 'Chirurgie', 'Chirurgie', 0, '', ''),
(255, 0, 247, 0, 'Frauenarzt', 'Frauenarzt', 0, '', ''),
(256, 0, 247, 0, 'Gastroenterologie', 'Gastroenterologie', 0, '', ''),
(257, 0, 247, 0, 'Phlebologie', 'Phlebologie', 0, '', ''),
(258, 0, 247, 0, 'Proktologie', '', 0, '', ''),
(259, 0, 247, 0, 'HIV, AIDS Schwerpunktpraxis & Beratung', 'HIV, AIDS Schwerpunktpraxis und Beratung', 0, '', ''),
(260, 0, 247, 0, 'HNO - Hals- Nasen und Ohrenärzte ', 'HNO - Hals- Nasen und Ohrenärzte ', 0, '', ''),
(261, 0, 247, 0, 'Hypnose geprüft', 'Hypnose geprüft', 0, '', ''),
(262, 0, 247, 0, 'Infektiologie', 'Infektiologie', 0, '', ''),
(263, 0, 247, 0, 'Innere Medizin & Internist', 'Innere Medizin und Internist', 0, '', ''),
(264, 0, 247, 0, 'Kardiologie ', 'Kardiologie ', 0, '', ''),
(265, 0, 247, 0, 'Laserbehandlung, Laserzentrum & Enthaarung mit Laser ', 'Laserbehandlung, Laserzentrum und Enthaarung mit Laser ', 0, '', ''),
(266, 0, 247, 0, 'Medizinische Labore', 'Medizinische Labore', 0, '', ''),
(267, 0, 247, 0, 'Neurologie', 'Neurologie', 0, '', ''),
(268, 0, 247, 0, 'Onkologie ', 'Onkologie ', 0, '', ''),
(269, 0, 247, 0, 'Orthopädie', 'Orthopädie', 0, '', ''),
(270, 0, 247, 0, 'Plastische Chirurgie', 'Plastische Chirurgie', 0, '', ''),
(271, 0, 247, 0, 'Pneumologie-, Lungenfacharzt-, Lungen- & Bronchialheilkunde', 'Pneumologie-, Lungenfacharzt-, Lungen- und Bronchialheilkunde', 0, '', ''),
(272, 0, 247, 0, 'Praxis für Paar- & Einzelberatung', 'Praxis für Paar- und Einzelberatung', 0, '', ''),
(273, 0, 247, 0, 'Psychiatrie & Psychologie', 'Psychiatrie und Psychologie', 0, '', ''),
(274, 0, 247, 0, 'Radiologie', 'Radiologie', 0, '', ''),
(275, 0, 247, 0, 'Schmerztherapie', 'Schmerztherapie', 0, '', ''),
(276, 0, 247, 0, 'Tierarzt', 'Tierarzt', 0, '', ''),
(277, 0, 247, 0, 'Ultraschall', 'Ultraschall', 0, '', ''),
(278, 0, 247, 0, 'Urologie', 'Urologie', 0, '', ''),
(279, 0, 247, 0, 'Zahnarzt & Kieferchirurgen', 'Zahnarzt und Kieferchirurgen', 0, '', ''),
(280, 0, 4, 0, 'Apotheken', 'Apotheken', 0, '', ''),
(281, 0, 4, 0, 'Ernährungsberatung & Diät', 'Ernährungsberatung und Diät', 0, '', ''),
(282, 0, 4, 0, 'Therapeuten', 'Therapeuten', 0, '', ''),
(283, 0, 282, 0, 'Angsttherapie', 'Angsttherapie', 0, '', ''),
(284, 0, 282, 0, 'Atemtherapie', 'Atemtherapie', 0, '', ''),
(285, 0, 282, 0, 'Logopädie', 'Logopädie', 0, '', ''),
(286, 0, 282, 0, 'Ergotherapie ', 'Ergotherapie ', 0, '', ''),
(287, 0, 282, 0, 'Physiotherapeuten & Krankengymnastik', 'Physiotherapeuten und Krankengymnastik', 0, '', ''),
(288, 0, 282, 0, 'Musiktherapie', 'Musiktherapie', 0, '', ''),
(289, 0, 282, 0, 'Sauerstofftherapie', 'Sauerstofftherapie', 0, '', ''),
(290, 0, 282, 0, 'Manuelle Therapie', 'Manuelle Therapie', 0, '', ''),
(291, 0, 4, 0, 'Alternative Medizin & TCM', 'Alternative Medizin und TCM', 0, '', ''),
(292, 0, 291, 0, 'Heilpraktiker', 'Heilpraktiker', 0, '', ''),
(293, 0, 291, 0, 'Heilpraktiker Psychologie', 'Heilpraktiker Psychologie', 0, '', ''),
(294, 0, 291, 0, 'Homöopathie', 'Homöopathie', 0, '', ''),
(295, 0, 291, 0, 'Naturheilkunde', 'Naturheilkunde', 0, '', ''),
(296, 0, 291, 0, 'Pflanzenheilkunde & Phytotherapie', 'Pflanzenheilkunde und Phytotherapie', 0, '', ''),
(297, 0, 291, 0, 'TCM - Traditionelle chinenische Medizin', 'TCM - Traditionelle chinenische Medizin', 0, '', ''),
(298, 0, 4, 0, 'Medizinische Fußpflege (Podologie)', 'Medizinische Fußpflege (Podologie)', 0, '', ''),
(299, 0, 4, 0, 'Krankenhäuser', 'Krankenhäuser', 0, '', ''),
(300, 0, 299, 0, 'Diagnoseklinik', 'Diagnoseklinik', 0, '', ''),
(301, 0, 299, 0, 'Tagesklinik', 'Tagesklinik', 0, '', ''),
(302, 0, 299, 0, 'Zahnklinik', 'Zahnklinik', 0, '', ''),
(303, 0, 299, 0, 'Reha-Kliniken', 'Reha-Kliniken', 0, '', ''),
(304, 0, 299, 0, 'Krankenhäuser', 'Krankenhäuser', 0, '', ''),
(305, 0, 299, 0, 'Dialyse & Dialysestationen', 'Dialyse und Dialysestationen', 0, '', ''),
(306, 0, 4, 0, 'Pharmakonzerne', 'Pharmakonzerne', 0, '', ''),
(307, 0, 4, 0, 'Pflege & Seniorenheime', 'Pflege und Seniorenheime', 0, '', ''),
(308, 0, 307, 0, 'Mehrgenerationenhaus', 'Mehrgenerationenhaus', 0, '', ''),
(309, 0, 307, 0, 'Pflegedienst & Krankenpflege', 'Pflegedienst und Krankenpflege', 0, '', ''),
(310, 0, 307, 0, 'Pflegeheime', 'Pflegeheime', 0, '', ''),
(311, 0, 307, 0, 'Seniorenheime & Altersruhesitz', 'Seniorenheime und Altersruhesitz', 0, '', ''),
(312, 0, 307, 0, 'Wohngemeinschaft altersgerecht', 'Wohngemeinschaft altersgerecht', 0, '', ''),
(313, 0, 4, 0, 'Essen auf Rädern', 'Essen auf Rädern', 0, '', ''),
(314, 0, 4, 0, 'Orthopädische Schuhmacher & Einlagen', 'Orthopädische Schuhmacher und Einlagen', 0, '', ''),
(315, 0, 4, 0, 'Optiker', 'Optiker', 0, '', ''),
(316, 0, 4, 0, 'Sanitätshäuser', 'Sanitätshäuser', 0, '', ''),
(317, 0, 4, 0, 'Hörgeräteservice & Hörgeärteakustiker', 'Hörgeräteservice und Hörgeärteakustiker', 0, '', ''),
(318, 0, 4, 0, 'Rettungsdienste', 'Rettungsdienste', 0, '', ''),
(319, 0, 5, 0, 'Organisationen & Vereine', 'Organisationen und Vereine', 0, '', ''),
(320, 0, 5, 0, 'Hospize ', 'Hospize ', 0, '', ''),
(321, 0, 5, 0, 'Jugendarbeit & Jugendzentren (Coming Out)', 'Jugendarbeit und Jugendzentren (Coming Out)', 0, '', ''),
(322, 0, 5, 0, 'Behörden', 'Behörden', 0, '', ''),
(323, 0, 5, 0, 'Soziale Projekte', 'Soziale Projekte', 0, '', ''),
(324, 0, 5, 0, 'Gesang & Musik ', 'Gesang und Musik ', 0, '', ''),
(325, 0, 5, 0, 'Schwule Sportorganisationen ', 'Schwule Sportorganisationen ', 0, '', ''),
(326, 0, 5, 0, 'Psychosoziale Beratung', 'Psychosoziale Beratung', 0, '', ''),
(327, 0, 5, 0, 'Sucht & Drogenberatung', 'Sucht und Drogenberatung', 0, '', ''),
(328, 0, 5, 0, 'CSD', 'CSD', 0, '', ''),
(329, 0, 5, 0, 'Essen & Trinken für Hilfsbedürftige', 'Essen und Trinken für Hilfsbedürftige', 0, '', ''),
(330, 0, 5, 0, 'Frauenprojekte', 'Frauenprojekte', 0, '', ''),
(331, 0, 5, 0, 'Stiftungen & Initiativen', 'Stiftungen und Initiativen', 0, '', ''),
(332, 0, 5, 0, 'Theater & Schauspiel', 'Theater und Schauspiel', 0, '', ''),
(333, 0, 5, 0, 'Hilfe & Beratung', 'Hilfe und Beratung', 0, '', ''),
(334, 0, 5, 0, 'Transidentität', 'Transidentität', 0, '', ''),
(335, 0, 5, 0, 'Anti Gewalt Projekte', 'Anti Gewalt Projekte', 0, '', ''),
(336, 0, 5, 0, 'AIDS, Gesundheit & Prävention', 'AIDS, Gesundheit und Prävention', 0, '', ''),
(337, 0, 5, 0, 'Parteien', 'Parteien', 0, '', ''),
(338, 0, 6, 0, 'Hotel, B&B, Gästehäuser & Appartments', 'Hotel, B&B, Gästehäuser und Appartments', 0, '', ''),
(339, 0, 338, 0, 'Hotels', 'Hotels', 0, '', ''),
(340, 0, 338, 0, 'Appartment', 'Appartment', 0, '', ''),
(341, 0, 338, 0, 'Bed & Breakfast, Pension & Zimmervermietung', 'Bed & Breakfast, Pension und Zimmervermietung', 0, '', ''),
(342, 0, 338, 0, 'Motel', 'Motel', 0, '', ''),
(343, 0, 338, 0, 'Reiterhof, Bauernhof & Farm', 'Reiterhof, Bauernhof und Farm', 0, '', ''),
(345, 0, 338, 0, 'Resort & Naturresort', 'Resort und Naturresort', 0, '', ''),
(346, 0, 338, 0, 'Zeltplatz & Camping', 'Zeltplatz und Camping', 0, '', ''),
(347, 0, 338, 0, 'Schlosshotel', 'Schlosshotel', 0, '', ''),
(348, 0, 338, 0, 'Kurhäuser & Kurhotel', 'Kurhäuser und Kurhotel', 0, '', ''),
(349, 0, 338, 0, 'Strandhäuser & Sommerhäuser', 'Strandhäuser und Sommerhäuser', 0, '', ''),
(350, 0, 338, 0, 'Kneippkuren', 'Kneippkuren', 0, '', ''),
(351, 0, 338, 0, 'Jungendherberge', 'Jungendherberge', 0, '', ''),
(352, 0, 338, 0, 'Seminar & Tagungshotel', 'Seminar und Tagungshotel', 0, '', ''),
(353, 0, 338, 0, 'Hotelvermittlung', 'Hotelvermittlung', 0, '', ''),
(354, 0, 6, 0, 'Tourist Information', 'Tourist Information', 0, '', ''),
(355, 0, 6, 0, 'Schiffsreisen, Kreuzfahrten & Yacht ', 'Schiffsreisen, Kreuzfahrten und Yacht ', 0, '', ''),
(356, 0, 6, 0, 'Reisebüro, Busreisen & Gayreisen', 'Reisebüro, Busreisen und Gayreisen', 0, '', ''),
(357, 0, 6, 0, 'Sprachreisen', 'Sprachreisen', 0, '', ''),
(358, 0, 6, 0, 'Tauchclubs ', 'Tauchclubs ', 0, '', ''),
(359, 0, 6, 0, 'Schwimmbad, Freibäder & Thermen', 'Schwimmbad, Freibäder und Thermen', 0, '', ''),
(360, 0, 6, 0, 'Guide & Stadtführungen', 'Guide & Stadtführungen', 0, '', ''),
(361, 0, 6, 0, 'Tauchclubs ', 'Tauchclubs ', 0, '', ''),
(362, 0, 6, 0, 'Flugbörsen', 'Flugbörsen', 0, '', ''),
(363, 0, 6, 0, 'Fluggesellschaft', 'Fluggesellschaft', 0, '', ''),
(364, 0, 6, 0, 'Badeseen & FKK', 'Badeseen und FKK', 0, '', ''),
(365, 0, 6, 0, 'Fahrrad Touren', 'Fahrrad Touren', 0, '', ''),
(366, 0, 6, 0, 'Mitfahrzentralen', 'Mitfahrzentralen', 0, '', ''),
(367, 0, 6, 0, 'Frauenreisen', 'Frauenreisen', 0, '', ''),
(368, 0, 6, 0, 'Wild- & Naturparks ', 'Wild- und Naturparks ', 0, '', ''),
(369, 0, 7, 0, 'Lebensmittel & Genußmittel ', 'Lebensmittel und Genußmittel ', 0, '', ''),
(370, 0, 369, 0, 'Bäckerei, Konditorei, Confiserie & Patisserie', 'Bäckerei, Konditorei, Confiserie und Patisserie', 0, '', ''),
(371, 0, 369, 0, 'Bio-Märkte, Reformhäuser & Naturkostladen', 'Bio-Märkte, Reformhäuser und Naturkostladen', 0, '', ''),
(372, 0, 369, 0, 'Metzger', 'Metzger', 0, '', ''),
(373, 0, 369, 0, 'Getränke', 'Getränke', 0, '', ''),
(374, 0, 369, 0, 'Käse & Milchprodukte ', 'Käse und Milchprodukte ', 0, '', ''),
(375, 0, 369, 0, 'Lebensmittel, Supermarkt, Feinkost & Tante Emma', 'Lebensmittel, Supermarkt, Feinkost und Tante Emma', 0, '', ''),
(376, 0, 369, 0, 'Schokolade & Chocolateria', 'Schokolade und Chocolateria', 0, '', ''),
(377, 0, 369, 0, 'Obst, Gemüse & Feinkost', 'Obst, Gemüse und Feinkost', 0, '', ''),
(378, 0, 369, 0, 'Tabakwaren, Raucherbedarf & Zeitschriften ', 'Tabakwaren, Raucherbedarf und Zeitschriften ', 0, '', ''),
(379, 0, 369, 0, 'Tee', 'Tee', 0, '', ''),
(380, 0, 369, 0, 'Vinothek, Weine & Spirituosen ', 'Vinothek, Weine und Spirituosen ', 0, '', ''),
(381, 0, 369, 0, 'Supermarkt', 'Supermarkt', 0, '', ''),
(382, 0, 369, 0, 'Tiefkühl Heimservice', 'Tiefkühl Heimservice', 0, '', ''),
(383, 0, 369, 0, 'Gewürze & Kräuter', 'Gewürze und Kräuter', 0, '', ''),
(384, 0, 7, 0, 'Wohnen & Einrichten ', 'Wohnen und Einrichten ', 0, '', ''),
(385, 0, 384, 0, 'Bad', '', 0, '', ''),
(386, 0, 384, 0, 'Parkett, Fußboden & Auslegware  ', 'Parkett, Fußboden und Auslegware  ', 0, '', ''),
(387, 0, 384, 0, 'Baumärkte', 'Baumärkte', 0, '', ''),
(388, 0, 384, 0, 'Beleuchtung & Licht ', 'Beleuchtung und Licht ', 0, '', ''),
(389, 0, 384, 0, 'Betten & Bettwaren', 'Betten und Bettwaren', 0, '', ''),
(390, 0, 384, 0, 'Designstore & Designmöbel', 'Designstore und Designmöbel', 0, '', ''),
(391, 0, 384, 0, 'Möbelhaus & Holzmöbel', 'Möbelhaus und Holzmöbel', 0, '', ''),
(392, 0, 384, 0, 'Farben & Lacke', 'Farben und Lacke', 0, '', ''),
(393, 0, 384, 0, 'Haushaltsgeräte ', 'Haushaltsgeräte ', 0, '', ''),
(394, 0, 384, 0, 'Keramik & Porzellan', 'Keramik und Porzellan', 0, '', ''),
(395, 0, 384, 0, 'Küchenstudio', 'Küchenstudio', 0, '', ''),
(396, 0, 384, 0, 'Kunst & Antiquitäten', 'Kunst und Antiquitäten', 0, '', ''),
(397, 0, 7, 0, 'Kosmetik & Beauty ', 'Kosmetik und Beauty ', 0, '', ''),
(398, 0, 397, 0, 'Parfüm & Kosmetik', 'Parfüm und Kosmetik', 0, '', ''),
(399, 0, 397, 0, 'Drugstore Kaufhaus ', 'Drugstore Kaufhaus ', 0, '', ''),
(400, 0, 7, 0, 'Freizeit & Hobbybedarf', 'Freizeit und Hobbybedarf', 0, '', ''),
(401, 0, 400, 0, 'Antiquariat für Bücher', 'Antiquariat für Bücher', 0, '', ''),
(402, 0, 400, 0, 'Buchhandlung ', 'Buchhandlung ', 0, '', ''),
(403, 0, 400, 0, 'Bürobedarf', 'Bürobedarf', 0, '', ''),
(404, 0, 400, 0, 'Campingbedarf', 'Campingbedarf', 0, '', ''),
(405, 0, 400, 0, 'Esoterik, Feng Shui & Alternativ', 'Esoterik, Feng Shui und Alternativ', 0, '', ''),
(406, 0, 400, 0, 'Fahrräder', 'Fahrräder', 0, '', ''),
(407, 0, 400, 0, 'Fitnessartikel & Sportgeräte  ', 'Fitnessartikel und Sportgeräte  ', 0, '', ''),
(408, 0, 400, 0, 'Foto & Filmfachhandel', 'Foto und Filmfachhandel', 0, '', ''),
(409, 0, 400, 0, 'Geschenkartikel & Andenken', 'Geschenkartikel und Andenken', 0, '', ''),
(410, 0, 400, 0, 'Hobby- & Freizeitbedarf', 'Hobby- und Freizeitbedarf', 0, '', ''),
(411, 0, 400, 0, 'Horror', 'Horror', 0, '', ''),
(412, 0, 400, 0, 'Kunsthandwerk, Künstlerbedarf & Basteln', 'Kunsthandwerk, Künstlerbedarf und Basteln', 0, '', ''),
(413, 0, 400, 0, 'Lotto & Glückspiel ', 'Lotto und Glückspiel ', 0, '', ''),
(414, 0, 400, 0, 'Musik CD, Musikinstrumente & DVD', 'Musik CD, Musikinstrumente und DVD', 0, '', ''),
(415, 0, 400, 0, 'Outdoor Ausrüstung ', 'Outdoor Ausrüstung ', 0, '', ''),
(416, 0, 400, 0, 'Papeterie, Schreibwaren & Bürobedarf', 'Papeterie, Schreibwaren und Bürobedarf', 0, '', ''),
(417, 0, 400, 0, 'Rainbow, Pride Store, CSD & Regenbogenartikel', 'Rainbow, Pride Store, CSD und Regenbogenartikel', 0, '', ''),
(418, 0, 400, 0, 'Spielwaren', 'Spielwaren', 0, '', ''),
(419, 0, 400, 0, 'Sportgeschäft', 'Sportgeschäft', 0, '', ''),
(420, 0, 400, 0, 'Wolle & Handarbeit', 'Wolle und Handarbeit', 0, '', ''),
(421, 0, 400, 0, 'Zeitungen & Broschüren', 'Zeitungen und Broschüren', 0, '', ''),
(422, 0, 400, 0, 'Zoofachgeschäft & Tiere', 'Zoofachgeschäft und Tiere', 0, '', ''),
(423, 0, 7, 0, 'Elektronik, Telefon & Computer', 'Elektronik, Telefon und Computer', 0, '', ''),
(424, 0, 423, 0, 'Autohaus ', 'Autohaus ', 0, '', ''),
(425, 0, 423, 0, 'Computer ', 'Computer ', 0, '', ''),
(426, 0, 423, 0, 'Copyshop, Kopieren & Textildruck', 'Copyshop, Kopieren und Textildruck', 0, '', ''),
(427, 0, 423, 0, 'Druckerzubehör   ', 'Druckerzubehör   ', 0, '', ''),
(428, 0, 423, 0, 'Elektrofachmarkt', 'Elektrofachmarkt', 0, '', ''),
(429, 0, 423, 0, 'Metallwaren, Eisenwaren & Stahlwaren Solingen  ', 'Metallwaren, Eisenwaren und Stahlwaren Solingen  ', 0, '', ''),
(430, 0, 423, 0, 'Telekommunikation', 'Telekommunikation', 0, '', ''),
(431, 0, 423, 0, 'Hardware & Software', 'Hardware und Software', 0, '', ''),
(432, 0, 423, 0, 'Video DVD Verleih & Kauf', 'Video DVD Verleih und Kauf', 0, '', ''),
(433, 0, 7, 0, 'Lifestyle & Bekleidung', 'Lifestyle und Bekleidung', 0, '', ''),
(434, 0, 433, 0, 'Arbeits- & Berufsbekleidung', 'Arbeits- und Berufsbekleidung', 0, '', ''),
(435, 0, 433, 0, 'Leder, Lederwaren, Taschen & Koffer', 'Leder, Lederwaren, Taschen und  Koffer', 0, '', ''),
(436, 0, 433, 0, 'Deko & Kostümverleih', 'Deko und Kostümverleih', 0, '', ''),
(437, 0, 433, 0, 'Factory Outlet', 'Factory Outlet', 0, '', ''),
(438, 0, 433, 0, 'Friseure & Perücken', 'Friseure und Perücken', 0, '', ''),
(439, 0, 433, 0, 'Junge Mode ', 'Junge Mode ', 0, '', ''),
(440, 0, 433, 0, 'Military', 'Military', 0, '', ''),
(441, 0, 433, 0, 'Herrenmode ', 'Herrenmode ', 0, '', ''),
(442, 0, 433, 0, 'Damenmode', 'Damenmode', 0, '', ''),
(443, 0, 433, 0, 'Hochzeit ', 'Hochzeit ', 0, '', ''),
(444, 0, 433, 0, 'Juweliere ', 'Juweliere ', 0, '', ''),
(445, 0, 433, 0, 'Schuhe', 'Schuhe', 0, '', ''),
(446, 0, 433, 0, 'Kostümverleih', 'Kostümverleih', 0, '', ''),
(447, 0, 433, 0, 'Second Hand, An+Verkauf & Gebrauchtwaren', 'Second Hand, An+Verkauf und Gebrauchtwaren', 0, '', ''),
(448, 0, 433, 0, 'Sportartikel- & bekleidung', 'Sportartikel- und bekleidung', 0, '', ''),
(449, 0, 433, 0, 'Wäsche, Unterwäsche & Bademode ', 'Wäsche, Unterwäsche und Bademode ', 0, '', ''),
(450, 0, 433, 0, 'Uhren & Wecker ', 'Uhren und Wecker ', 0, '', ''),
(451, 0, 433, 0, 'Trachten ', 'Trachten ', 0, '', ''),
(452, 0, 433, 0, 'Jeansläden', 'Jeansläden', 0, '', ''),
(453, 0, 7, 0, 'Garten & Pflanzen', 'Garten und Pflanzen', 0, '', ''),
(454, 0, 453, 0, 'Blumen & Floristik', 'Blumen und Floristik', 0, '', ''),
(455, 0, 453, 0, 'Gartencenter & Pflanzen', 'Gartencenter und Pflanzen', 0, '', ''),
(456, 0, 453, 0, 'Gartenmöbel', 'Gartenmöbel', 0, '', ''),
(457, 0, 453, 0, 'Kräuter & Heilkräuter Pflanzen', 'Kräuter & Heilkräuter Pflanzen', 0, '', ''),
(458, 0, 453, 0, 'Baumschule', 'Baumschule', 0, '', ''),
(459, 0, 453, 0, 'Gartengestaltung', 'Gartengestaltung', 0, '', ''),
(460, 0, 7, 0, 'Autohaus & Motorräder', 'Autohaus und Motorräder', 0, '', ''),
(461, 0, 7, 0, 'Piercing & Tattoo', 'Piercing und Tattoo', 0, '', ''),
(462, 0, 7, 0, 'Hotel- & Gastronomiebedarf', 'Hotel- und Gastronomiebedarf', 0, '', ''),
(463, 0, 8, 0, 'Logistik', 'Logistik', 0, '', ''),
(464, 0, 26, 0, 'Redakteure', 'Redakteure', 0, '', ''),
(465, 0, 247, 0, 'Reisemedizin & Tropenmedizin', 'Reisemedizin und Tropenmedizin', 0, '', ''),
(467, 0, 4, 0, 'Labor & Labormedizin', 'Labor und Labormedizin', 0, '', '');



-- -----------------------------------------------------
-- Table `tree_nodes`.`listings`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `tree_nodes`.`listings` (
  `id` INT(11) NOT NULL ,
  `level_id` INT(11) NOT NULL ,
  `owner_id` INT(11) NOT NULL ,
  `title` VARCHAR(255) NOT NULL ,
  `seo_title` VARCHAR(255) NOT NULL ,
  `listing_description` TEXT NOT NULL ,
  `listing_meta_description` TEXT NOT NULL ,
  `listing_keywords` TEXT NOT NULL ,
  `url` VARCHAR(55) NOT NULL ,
  `email1` VARCHAR(55) NOT NULL ,
  `email2` VARCHAR(55) NULL DEFAULT NULL ,
  `social1` VARCHAR(55) NULL DEFAULT NULL ,
  `social2` VARCHAR(55) NULL DEFAULT NULL ,
  `address` VARCHAR(155) NOT NULL ,
  `zip` VARCHAR(11) NOT NULL ,
  `city` VARCHAR(55) NOT NULL ,
  `phone` VARCHAR(55) NOT NULL ,
  `mobil` TEXT NOT NULL ,
  `fax` VARCHAR(55) NOT NULL ,
  `opening_days` VARCHAR(55) NOT NULL ,
  `opening_times` VARCHAR(55) NOT NULL ,
  `heading` VARCHAR(55) NOT NULL ,
  `description` VARCHAR(400) NOT NULL ,
  `targetgroups` VARCHAR(55) NOT NULL ,
  `age` VARCHAR(55) NOT NULL ,
  `spez` VARCHAR(55) NOT NULL ,
  `location` VARCHAR(55) NOT NULL ,
  `languages` VARCHAR(55) NOT NULL ,
  `payment` VARCHAR(25) NOT NULL ,
  `country` VARCHAR(55) NOT NULL ,
  `paid` INT(11) NOT NULL ,
  `web_visit_count` INT(11) NOT NULL ,
  `is_featured` INT(11) NOT NULL ,
  `logo_file` VARCHAR(255) NOT NULL ,
  `status` VARCHAR(255) NOT NULL ,
  `creation_date` VARCHAR(55) NOT NULL ,
  `expiration_date` DATETIME NOT NULL ,
  `last_modified_date` DATETIME NOT NULL ,
  `was_prolonged_times` INT(11) NOT NULL ,
  `levels_id` INT(11) NOT NULL ,
  `category_id` INT(15) NOT NULL ,
  PRIMARY KEY (`id`, `levels_id`) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
